routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
// Route::group(['middleware' => 'App\Http\Middleware\UserMiddleware'], function()
// {

Route::resource('web','RegisterController');

// });

// Route::group(['middleware' => 'App\Http\Middleware\AdminMiddleware'], function()
// {

Route::resource('job','jobController');
Route::get('jobview','jobController@jobview');
Route::post('jobseeker/{id}','jobController@jobseeker');
Route::get('/delete/{id}','jobController@destroy')->name('delete');
Route::get('jobseekerview','callLetterController@jobseekerview');

Route::get('send_call_letter','interviewController@callletter');
Route::post('send_call_letter','interviewController@send_letter');
Route::get('interview_view','interviewController@viewCandidates');
Route::get('interview_status','interviewController@interview_status');
Route::get('view_details','interviewController@view_details');
Route::get('save/{id}','interviewController@saveData');
Route::get('{id}/status_show','interviewController@status_show');
Route::post('shortlist/{id}','interviewController@shortList');
Route::resource('interview','interviewController');
Route::get('show_all_status','interviewController@showAllstatus');


Route::resource('resume','ResumeController');
Route::get('viewresume','ResumeController@viewresume');
Route::get('search','ResumeController@search_resume');
Route::get('find','ResumeController@filter_resume');
Route::post('send','mailController@send');
Route::get('sendMail/{id}','callLetterController@send');

Route::get('email','mailController@email');
Route::post('verify','mailController@verify');

// });




//Route::get('view_details','RegisterController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/interviewController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Contracts\Validation\Validator;
use App\Interview;
use App\RegisterForm;
use App\User;
use DB;
use Session;
use App\Interviewstatus;
use App\shortlistCandidates;
class interviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $select=shortlistCandidates::get();
        return view('interview.schedule_interview')->with('select',$select);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    $this->validate($request, [
    'name' => 'required|max:255',
    'interview_code'=>'required',
    'post'=>'required',
    'date'=>'required',
    'venu'=>'required',
    'rounds'=>'required',
    'mail_id'=>'required'

    
]);

    $interview = new interview;
    $interview->name = $request->name;
    $interview->interview_code = $request->interview_code;
    $interview->post = $request->post;
    $interview->date= $request->date;
    $interview->venu= $request->venu;
    $interview->rounds= $request->rounds;
    $interview->mail_id= $request->mail_id;
    $interview->save();
    Session::flash('message1', ' interview has been Successfully Added!');
    return redirect('/interview');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $details = RegisterForm::find($id);
        
        return view('interview.view_details',compact('details'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit_details = shortlistCandidates::where('select_id',$id)->first();
        return view('interview.edit_interview_status')->with('edit_details',$edit_details);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)

    {
        //return redirect('interview.interview_status');
        //return 'hai';
        $item=Interviewstatus::find($id);
        $item->attended = $request['radiotrue'];
        $item->status = $request['selection'];
        $item->comment = $request['comment'];
        $item->update();
        Session::flash('message1', ' data has been updated.');
         return redirect('interview_status');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
            
    }
    public function callletter()
    {

        $SendCallLetters = Interview::get();
        return view('interview.send_call_letter')->with('SendCallLetters', $SendCallLetters);
        
    }
     public function viewCandidates()
    {
        $jobs = RegisterForm::get();
        return view('interview.applaid_candidates_view')->with('jobs', $jobs);
    }
     public function interview_status()
    {
        $jobs = Interview::get();
        return view('interview.interview_status')->with('jobs', $jobs);
    }
   
    public function saveData(Request $request, $id)
    {
       $save_id = Interview::where('id',$id)->first();
       $key=Interviewstatus::where('interview_id',$save_id->id)->count();
         if ($key==0)
         {
            $selectdata = new Interviewstatus;
            $selectdata->name=$save_id->name;
            $selectdata->interview_id=$save_id->id;
            $selectdata->interview_code=$save_id->interview_code;
            $selectdata->post=$save_id->post;
            $selectdata->date=$save_id->date;
            $selectdata->venu=$save_id->venu;
            $selectdata->attended = $request['radiotrue'];
            $selectdata->status = $request['selection'];
            $selectdata->comment = $request['comment'];
            $selectdata->save();
            Session::flash('message1', ' data has been  saved.');
            return redirect('interview_status');
        }

        else
       {
          Session::flash('message1', ' data has been already saved.');
           return redirect('interview_status');

        } 
    }
    public function shortList(Request $request ,$id)
    {
        $candidates=shortlistCandidates::where('id',$id)->count();
        if($candidates == 0)
        {
            $name=DB::table('register_forms')->where('id',$id)->value('name');
            $interview = new shortlistCandidates;
            $interview->id = $id;
            $interview->name = $name;
            $interview->save();
            Session::flash('message1', ' Candidate has been Successfully Added!');
            return redirect('/interview_view'); 
        }
        else
        {
           Session::flash('message1', ' Candidate already exits!');
            return redirect('/interview_view');   
        }    
}


 public function status_show($id)
    {
         $status = Interviewstatus::find($id);
         return view('interview.show_status_details')->with('status', $status);
        
    }
    public function showAllstatus()
    {
         $details = Interviewstatus::get(); 
        return view('interview.show_all_status')->with('details', $details);    

    }
   



   
    
}

resources/views/interview/applaid_candidates_view.blade.php
@extends('Template.app')
@section('body')

  <div class="panel panel-primary col-md-6 col-md-offset-3">
  @if (Session::has('message1'))
          <div class="alert alert-danger">{{ Session::get('message1') }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          @endif
    <div class="panel-body">
     <form> 
     {{csrf_field()}}         
      <table align="center" class="table table-condensed">
        <thead class="bg-primary">
          <tr>
            <th>Name</th>
            <th>Post</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
        @foreach($jobs as $job)
      <td>{{ $job->name}} </td>
      <td>{{ $job->applied_position}}</td>
      <td><a href="{{url('interview/'.$job->id)}}" class="btn btn-success" role="button">view details</a></td>
    </tr>
    @endforeach

        </tbody>
      </table>
    </div>
  </div>
@endsection

resources/views/interview/edit_interview_status.blade.php
  <!DOCTYPE html>
<html lang="en">
<head>
  <title>Career Management</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
    <div class="panel panel-primary col-md-6 col-md-offset-3">
      <div class="panel-body">
       <form class="form-horizontal" method="post" action="{{route('interview.update',$edit_details->id)}}">

        {{method_field('PUT')}}
        {{csrf_field()}}
       <div class="form-group">
      <label for="name">Name:</label>
      {{$edit_details->name}}
      </div>
      <div class="form-group">
      <label for="name">Interview code:</label>
      {{$edit_details->interview_code}}
      </div>
      <div class="form-group">
      <label for="name">Post:</label>
      {{$edit_details->post}}
      </div>
      <div class="form-group">
     
      <label for="name">Date and Time:</label>
      {{$edit_details->date}}
      </div>

         <div class="form-group">
         <label for="attended">Attended</label>
          <label><input type="radio" name="radiotrue" value="attended">True @if($edit_details->attended=='attended')  @endif</label>
          
          <label><input type="radio" name="radiotrue" value="not attended" >False @if($edit_details->attended=='not attended')  @endif</label>
        </div>
<div class="form-group">
     <label for="attended">Status</label>
        <select class="selectpicker" name="selection">---select the option---
          <option value="selected">selected</option>
          <option value="selected">Not selected</option>
        </select>
</div>
      <div class="form-group">
      <label for="attended">Comment</label>
          <textarea class="form-control" rows="3" name="comment" id="comment" value="{{$edit_details->comments}}"></textarea>
      </div>
      <div class="form-group">
      <button type="submit" class="btn btn-primary">Edit</button>
      </div>
       </form>
</div>
</div>
</html>
 
 

resources/views/interview/interview_status.blade.php
@extends('Template.app')
@section('body')
    
 <div class="panel panel-primary col-md-10 col-md-offset-2">
 @if (Session::has('message1'))
          <div class="alert alert-danger">{{ Session::get('message1') }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          @endif
    <div class="panel-body">
           
  <table class="table table-condensed">
    <thead class="bg-primary">
      <tr>
        <th>Sl no</th>
        <th>Name</th>
        <th>Interview Code</th>
        <th>Post</th>
        <th>Date/time</th>
        <th>Attended</th>
        <th>Status</th>
        <th>Comment</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    <tr>
    @foreach($jobs as $job)
      <td>{{ $job->id}} </td>
      <td>{{ $job->name}}</td>
      <td>{{ $job->interview_code}}</td>
      <td>{{ $job->post}}</td>
      <td>{{ $job->date}}</td>
    
  <form method="put" action="{{url('save/'.$job->id)}}">
        {{csrf_field()}}
        <td><div class="radio">
          <label><input type="radio" name="radiotrue">Attended</label>
          <label><input type="radio" name="radiotrue">Not Attended</label>
        </div></td>
        <td><select class="selectpicker" name="selection">---select the option---
          <option>selected</option>
          <option>Not selected</option>
        </select>
      </td>
      <td><textarea class="form-control" rows="3" name="comment" id="comment"></textarea></td>
      <td><button type="submit" class=" btn btn-success" value="Save" name="" id="$job->id">Save</button></td>
      <td><a href="{{url('interview/'.$job->id.'/edit')}}" class="btn btn-success" role="button">Edit</a></td>
    </tr> 
  </td>
</form>
 @endforeach
</tbody>

</table>
<a href="{{url('show_all_status/')}}"> <button type="button" class="btn btn-primary" > Show all status</button></a>
</div>
</div>
@endsection

resources/views/interview/schedule_interview.blade.php
  @extends('Template.app')
  @section('body')
    <div class="panel panel-primary col-md-6 col-md-offset-3">
      
      <div class="panel-body">
       <form action="{{url('interview')}}" method="post">
       {{csrf_field()}}

@if (Session::has('message1'))
    <div class="alert alert-success">{{ Session::get('message1') }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
    @endif</div>


       
      <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
        <label for="name">Name</label><br>
        <select name="name" class="col-md-9" id="" >
                <option value="0" selected="selected">select</option> 
                @foreach($select as $select) 
                <option id="name" value="{{$select->name}}">{{$select->name}}
                </option> 
                  @endforeach
        </select>
        <br>
        @if ($errors->has('name'))
            <span class="help-block">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
      </div>

       <div class="form-group {{ $errors->has('interview_code') ? ' has-error' : '' }}">
        <label for="interview_code">Interview Code</label>
        <input type="text" name="interview_code" class="form-control" id="usr">
        @if ($errors->has('interview_code'))
            <span class="help-block">
                <strong>{{ $errors->first('interview_code') }}</strong>
            </span>
        @endif
      </div>

      <div class="form-group {{ $errors->has('post') ? ' has-error' : '' }}">
        <label for="post">Post</label>
        <input type="text" name="post" class="form-control" id="post">
        @if ($errors->has('post'))
            <span class="help-block">
                <strong>{{ $errors->first('post') }}</strong>
            </span>
        @endif
      </div>

      <div class="form-group {{ $errors->has('date') ? ' has-error' : '' }}">
        <label for="usr">Date/Time</label>
        <input type="text" name="date" class="form-control" id="datepicker" >
        @if ($errors->has('date'))
            <span class="help-block">
                <strong>{{ $errors->first('date') }}</strong>
            </span>
        @endif
      </div>

      <div class="form-group {{ $errors->has('venu') ? ' has-error' : '' }}">
        <label for="usr">Venu</label>
        <input type="text" name="venu" class="form-control" id="usr">
        @if ($errors->has('venu'))
            <span class="help-block">
                <strong>{{ $errors->first('venu') }}</strong>
            </span>
        @endif
      </div>

      <div class="form-group {{ $errors->has('rounds') ? ' has-error' : '' }}">
        <label for="usr">Rounds</label>
        <input type="text" name="rounds" class="form-control" id="usr">
         @if ($errors->has('rounds'))
            <span class="help-block">
                <strong>{{ $errors->first('rounds') }}</strong>
            </span>
        @endif
      </div>

      <div class="form-group {{ $errors->has('mail_id') ? ' has-error' : '' }}">
        <label for="email-id">Email id</label>
        <input type="text" name="mail_id" class="form-control" id="usr">
        @if ($errors->has('mail_id'))
            <span class="help-block">
                <strong>{{ $errors->first('mail_id') }}</strong>
            </span>
        @endif
      </div>
      
    <div class="form-group">
        <button type="submit" class="btn btn-info">Submit</button>
      </form>
      </div>
    </div>
    
  </div>
@endsection

resources/views/interview/send_call_letter.blade.php
@extends('Template.app')
@section('body')
<div class="panel-group">
       <div class="panel panel-primary col-md-10 col-md-offset-2">
    <div class="panel-body">

  <table class="table table-condensed">
    <thead class="bg-primary">
      <tr>
        <th>Sl no</th>
        <th>Name</th>
        <th>Interview Code</th>
         <th>Post</th>
        <th>Date/time</th>
        <th>Venu</th>
        <th>Rounds</th>
        <th>Email</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    <tr>
    @foreach($SendCallLetters as $SendCallLetter)    
      <td>{{ $SendCallLetter->id}} </td>
      <td>{{ $SendCallLetter->name}} </td>
      <td>{{ $SendCallLetter->interview_code}}</td>
      <td>{{ $SendCallLetter->post}}</td> 
      <td>{{ $SendCallLetter->date}}</td>
      <td>{{ $SendCallLetter->venu}}</td>
      <td>{{ $SendCallLetter->rounds}}</td>
       <td>{{ $SendCallLetter->mail_id}}</td> 
        <td>
<a href="{{url('sendMail/'.$SendCallLetter->id.'')}}"> <button type="button" class="btn btn-primary" > Send</button></a>
</td>   
    </div>
  </div>    
</tr>
@endforeach
    </tbody>
    
  </table>
  
    </div>  
    </div>
  </div>
  </div>
  </div>

@endsection

resources/views/interview/show_all_status.blade.php
@extends('Template.app')
@section('body')
<div class="panel-group">
       <div class="panel panel-primary col-md-10 col-md-offset-2">
    <div class="panel-body">

  <table class="table table-condensed">
    <thead class="bg-primary">
      <tr>
        <th>Sl no</th>
        <th>Name</th>
        <th>Interview Code</th>
         <th>Post</th>
        <th>Date/time</th>
        <th>Attended or not</th>
         <th>Status</th>
          <th>Comments</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
     <tr>
    @foreach($details as $details)    
      <td>{{ $details->id}} </td>
       <td>{{ $details->name}} </td>
       <td>{{ $details->interview_code}}</td>
       <td>{{ $details->post}}</td>
       <td>{{ $details->date}}</td>
       <td>{{ $details->attended}}</td>
       <td>{{ $details->status}}</td>
       <td>{{ $details->comment}}</td>

      </tr>
      @endforeach  
    </div>
    <div class="col-md-offset-4">
  <button type="submit" action="send"  class="btn btn-info btn-md">Generate pdf</button>  
  </div>
</tbody>


@endsection

resources/views/interview/show_status_details.blade.php
@extends('Template.app')
@section('body')
<div class="panel-group">
       <div class="panel panel-primary col-md-10 col-md-offset-2">
    <div class="panel-body">

  <table class="table table-condensed">
    <thead class="bg-primary">
      <tr>
        <th>Sl no</th>
        <th>Name</th>
        <th>Interview Code</th>
         <th>Post</th>
        <th>Date/time</th>
        <th>Venu</th>
        <th>Rounds</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
    <tr>
    @foreach($details as $details)    
      <td>{{ $details->id}} </td>
      <td>{{ $details->name}} </td>
      <td>{{ $details->interview_code}}</td>
      <td>{{ $details->post}}</td> 
      <td>{{ $details->date}}</td>
      <td>{{ $details->venu}}</td>
      <td>{{ $details->rounds}}</td>
       <td>{{ details->mail_id}}</td>    
    </div>
  </div>    
</tr>
@endforeach
    </tbody>
  </table>
  <div class="col-md-offset-4">
  <button type="submit" action="send"  class="btn btn-info btn-md">Send Call Letter</button>    
    </div>
  </div>
  </div>
  </div>

@endsection

resources/views/interview/test.blade.php
@extends('Template.app')

resources/views/interview/test_upload.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Test upload</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
</head>
<body>
<br>
<div class="col-lg-offset-4 col-lg-4">
	<center><h1>File upload</center></h1>
	<form action="/upload" enctype="multipart/form-data" method="post">
	{{csrf_field()}}
	<input type="text" name="testname">
	<input type="file" name="image"><br>
	<button type="submit"  value="upload" class=" btn-success col-md-offset-3">Save</button>
	</form>


</div>

</body>
</html>

resources/views/interview/view_details.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Career Management</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<div class="panel panel-primary col-md-8 col-md-offset-3">
  <div class="panel-body">
    <form method="post" action="{{url('shortlist/'.$details->id)}}"> 
    {{csrf_field()}}   
      <table align="center" class="table table-condensed">
        <thead class="bg-primary">
          <tr>
          <th>Id</th>
            <th>Name</th>
            <th>Applied position</th>
            <th>photo</th>
            <th>Resume</th>
          </tr>
        </thead>
        <tbody>
        <td>{{$details->id}}</td>
        <td>{{$details->name}}</td>
        <td>{{$details->applied_position}}</td>
       <td><img src="<?php echo asset("storage/Photo/$details->photo_path")?>" width="100px"></img></td>
        <td><a href="{{asset('storage/Resume')}}/{{$details->resume_path}}">{{$details->resume_path}}</a></td>

        <td><button type="submit" action=""  class="btn btn-info btn-md">Add</button></td>
        </form>
        </tbody>
      </table>
    </div>
  </div>

</form>
</div></div>
</html>